// Command reset генерирует Reset-методы для структур с директивой generate:reset.
package main

import (
	"bytes"
	"errors"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"io/fs"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	resetDirective      = "generate:reset"
	generatedFileName   = "reset.gen.go"
	generatedFileHeader = "// Code generated by cmd/reset; DO NOT EDIT.\n"
)

func main() {
	if err := run(os.Args[1:]); err != nil {
		log.Fatal(err)
	}
}

func run(args []string) error {
	if len(args) > 1 {
		return errors.New("usage: reset [root]")
	}

	root := "."
	if len(args) == 1 {
		root = args[0]
	}

	return generate(root)
}

func generate(root string) error {
	root, err := filepath.Abs(root)
	if err != nil {
		return err
	}

	return filepath.WalkDir(root, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if !entry.IsDir() {
			return nil
		}
		if shouldSkipDir(root, path, entry.Name()) {
			return filepath.SkipDir
		}

		return generatePackage(path)
	})
}

func shouldSkipDir(root, path, name string) bool {
	if path == root {
		return false
	}

	return name == ".git" || name == "vendor" || name == "testdata"
}

func generatePackage(dir string) error {
	fset := token.NewFileSet()
	filesByPackage, err := parsePackageFiles(fset, dir)
	if err != nil {
		return err
	}
	if len(filesByPackage) == 0 {
		return nil
	}

	names := make([]string, 0, len(filesByPackage))
	for name := range filesByPackage {
		names = append(names, name)
	}
	sort.Strings(names)

	if len(names) > 1 {
		return fmt.Errorf("%s: found multiple non-test packages: %s", dir, strings.Join(names, ", "))
	}

	packageName := names[0]
	packageFiles := filesByPackage[packageName]
	structs := findResetStructs(packageFiles)
	if len(structs) == 0 {
		if removeErr := removeGeneratedFile(dir); removeErr != nil {
			return removeErr
		}
		return nil
	}

	src, renderErr := renderPackage(packageName, packageFiles, structs)
	if renderErr != nil {
		return renderErr
	}
	if writeErr := os.WriteFile(filepath.Join(dir, generatedFileName), src, 0o644); writeErr != nil {
		return writeErr
	}

	return nil
}

func parsePackageFiles(fset *token.FileSet, dir string) (map[string][]*ast.File, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}

	files := make(map[string][]*ast.File)
	for _, entry := range entries {
		info, err := entry.Info()
		if err != nil {
			return nil, err
		}
		if !isSourceFile(info) {
			continue
		}

		path := filepath.Join(dir, entry.Name())
		file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			return nil, err
		}

		files[file.Name.Name] = append(files[file.Name.Name], file)
	}

	return files, nil
}

func isSourceFile(info fs.FileInfo) bool {
	name := info.Name()
	return !info.IsDir() &&
		strings.HasSuffix(name, ".go") &&
		!strings.HasSuffix(name, "_test.go") &&
		name != generatedFileName
}

func removeGeneratedFile(dir string) error {
	path := filepath.Join(dir, generatedFileName)
	data, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return err
	}
	if !bytes.HasPrefix(data, []byte(generatedFileHeader)) {
		return nil
	}

	return os.Remove(path)
}

func findResetStructs(files []*ast.File) []resetStructDecl {
	var structs []resetStructDecl

	for _, file := range files {
		structs = append(structs, findResetStructsInFile(file)...)
	}

	sort.Slice(structs, func(i, j int) bool {
		return structs[i].name < structs[j].name
	})

	return structs
}

func findResetStructsInFile(file *ast.File) []resetStructDecl {
	var structs []resetStructDecl

	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}

		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			structType, ok := typeSpec.Type.(*ast.StructType)
			if !ok || !hasResetDirective(genDecl.Doc, typeSpec.Doc) {
				continue
			}

			structs = append(structs, resetStructDecl{
				name:       typeSpec.Name.Name,
				typeParams: typeSpec.TypeParams,
				fields:     structType.Fields,
			})
		}
	}

	return structs
}

func hasResetDirective(groups ...*ast.CommentGroup) bool {
	for _, group := range groups {
		if group == nil {
			continue
		}
		for _, comment := range group.List {
			if strings.TrimSpace(strings.TrimPrefix(comment.Text, "//")) == resetDirective {
				return true
			}
		}
	}

	return false
}

type resetStructDecl struct {
	name       string
	typeParams *ast.FieldList
	fields     *ast.FieldList
}

func renderPackage(pkgName string, files []*ast.File, structs []resetStructDecl) ([]byte, error) {
	g := codeGenerator{
		pkgName:      pkgName,
		knownTypes:   collectTypeDeclarations(files),
		resetMethods: collectResetMethods(files, structs),
	}
	g.render(structs)

	src, err := format.Source(g.buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated reset code: %w\n%s", err, g.buf.String())
	}

	return src, nil
}

type codeGenerator struct {
	buf          bytes.Buffer
	pkgName      string
	knownTypes   typeRegistry
	resetMethods map[string]struct{}
}

func (g *codeGenerator) render(structs []resetStructDecl) {
	methods := g.renderMethods(structs)

	g.buf.WriteString(generatedFileHeader)
	g.buf.WriteByte('\n')
	fmt.Fprintf(&g.buf, "package %s\n\n", g.pkgName)
	g.buf.Write(methods)
}

func (g *codeGenerator) renderMethods(structs []resetStructDecl) []byte {
	var methods bytes.Buffer

	for _, item := range structs {
		fmt.Fprintf(&methods, "func (v *%s) Reset() {\n", receiverType(item))
		fmt.Fprintf(&methods, "if v == nil {\nreturn\n}\n\n")

		g.renderFieldList(&methods, "v", item.fields)
		fmt.Fprintf(&methods, "}\n\n")
	}

	return methods.Bytes()
}

type typeRegistry map[string]ast.Expr

func collectTypeDeclarations(files []*ast.File) typeRegistry {
	types := make(typeRegistry)

	for _, file := range files {
		for _, decl := range file.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}

			for _, spec := range genDecl.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if ok {
					types[typeSpec.Name.Name] = typeSpec.Type
				}
			}
		}
	}

	return types
}

func collectResetMethods(files []*ast.File, structs []resetStructDecl) map[string]struct{} {
	methods := make(map[string]struct{}, len(structs))

	for _, item := range structs {
		methods[item.name] = struct{}{}
	}

	for _, file := range files {
		for _, decl := range file.Decls {
			funcDecl, ok := decl.(*ast.FuncDecl)
			if !ok || !isResetMethodDecl(funcDecl) {
				continue
			}

			name := receiverBaseName(funcDecl.Recv.List[0].Type)
			if name != "" {
				methods[name] = struct{}{}
			}
		}
	}

	return methods
}

func isResetMethodDecl(decl *ast.FuncDecl) bool {
	return decl.Recv != nil &&
		len(decl.Recv.List) > 0 &&
		decl.Name.Name == "Reset" &&
		(decl.Type.Params == nil || len(decl.Type.Params.List) == 0) &&
		(decl.Type.Results == nil || len(decl.Type.Results.List) == 0)
}

func receiverBaseName(expr ast.Expr) string {
	switch typ := expr.(type) {
	case *ast.Ident:
		return typ.Name
	case *ast.StarExpr:
		return receiverBaseName(typ.X)
	case *ast.IndexExpr:
		return receiverBaseName(typ.X)
	case *ast.IndexListExpr:
		return receiverBaseName(typ.X)
	}

	return ""
}

func (r typeRegistry) underlying(expr ast.Expr) ast.Expr {
	return r.underlyingWithSeen(expr, make(map[string]struct{}))
}

func (r typeRegistry) underlyingWithSeen(expr ast.Expr, seen map[string]struct{}) ast.Expr {
	ident, ok := expr.(*ast.Ident)
	if !ok {
		return expr
	}
	if _, seenBefore := seen[ident.Name]; seenBefore {
		return expr
	}

	target, found := r[ident.Name]
	if !found {
		return expr
	}

	seen[ident.Name] = struct{}{}
	return r.underlyingWithSeen(target, seen)
}

func receiverType(item resetStructDecl) string {
	names := typeParamNames(item.typeParams)
	if len(names) == 0 {
		return item.name
	}

	return fmt.Sprintf("%s[%s]", item.name, strings.Join(names, ", "))
}

func typeParamNames(typeParams *ast.FieldList) []string {
	if typeParams == nil {
		return nil
	}

	var names []string
	for _, field := range typeParams.List {
		for _, name := range field.Names {
			names = append(names, name.Name)
		}
	}

	return names
}

func (g *codeGenerator) renderFieldList(buf *bytes.Buffer, owner string, fields *ast.FieldList) {
	if fields == nil {
		return
	}

	for _, field := range fields.List {
		names := fieldNames(field)
		for _, name := range names {
			g.renderReset(buf, owner+"."+name, field.Type)
		}
	}
}

func fieldNames(field *ast.Field) []string {
	if len(field.Names) > 0 {
		names := make([]string, 0, len(field.Names))
		for _, name := range field.Names {
			if name.Name != "_" {
				names = append(names, name.Name)
			}
		}
		return names
	}

	name := embeddedFieldName(field.Type)
	if name == "" {
		return nil
	}

	return []string{name}
}

func embeddedFieldName(expr ast.Expr) string {
	switch typ := expr.(type) {
	case *ast.Ident:
		return typ.Name
	case *ast.SelectorExpr:
		return typ.Sel.Name
	case *ast.StarExpr:
		return embeddedFieldName(typ.X)
	case *ast.IndexExpr:
		return embeddedFieldName(typ.X)
	case *ast.IndexListExpr:
		return embeddedFieldName(typ.X)
	}

	return ""
}

func (g *codeGenerator) renderReset(buf *bytes.Buffer, target string, fieldType ast.Expr) {
	switch typ := fieldType.(type) {
	case *ast.ArrayType:
		if typ.Len == nil {
			fmt.Fprintf(buf, "%s = %s[:0]\n", target, target)
			return
		}
		g.renderZeroAssignment(buf, target, fieldType)
	case *ast.MapType:
		fmt.Fprintf(buf, "clear(%s)\n", target)
	case *ast.StarExpr:
		g.renderPointerReset(buf, target, typ.X)
	case *ast.StructType:
		g.renderFieldList(buf, target, typ.Fields)
	case *ast.Ident:
		g.renderIdentReset(buf, target, typ)
	default:
		g.renderResetterOrZero(buf, target, fieldType)
	}
}

func (g *codeGenerator) renderPointerReset(buf *bytes.Buffer, target string, elem ast.Expr) {
	fmt.Fprintf(buf, "if %s != nil {\n", target)
	g.renderPointerValueReset(buf, target, elem)
	fmt.Fprintf(buf, "}\n")
}

func (g *codeGenerator) renderPointerValueReset(buf *bytes.Buffer, target string, elem ast.Expr) {
	switch elem := elem.(type) {
	case *ast.ArrayType:
		if elem.Len == nil {
			fmt.Fprintf(buf, "*%s = (*%s)[:0]\n", target, target)
			return
		}
		g.renderPointerZeroAssignment(buf, target, elem)
	case *ast.MapType:
		fmt.Fprintf(buf, "clear(*%s)\n", target)
	case *ast.StarExpr:
		g.renderPointerReset(buf, "*"+target, elem.X)
	case *ast.StructType:
		g.renderFieldList(buf, "(*"+target+")", elem.Fields)
	case *ast.Ident:
		g.renderPointerIdentReset(buf, target, elem)
	default:
		g.renderResetterOrPointerZero(buf, target, elem)
	}
}

func (g *codeGenerator) renderIdentReset(buf *bytes.Buffer, target string, ident *ast.Ident) {
	if literal, ok := zeroLiteral(ident.Name); ok {
		fmt.Fprintf(buf, "%s = %s\n", target, literal)
		return
	}
	if g.hasResetMethod(ident.Name) {
		fmt.Fprintf(buf, "%s.Reset()\n", selectorTarget(target))
		return
	}

	switch underlying := g.knownTypes.underlying(ident).(type) {
	case *ast.ArrayType:
		if underlying.Len == nil {
			fmt.Fprintf(buf, "%s = %s[:0]\n", target, target)
			return
		}
	case *ast.MapType:
		fmt.Fprintf(buf, "clear(%s)\n", target)
		return
	case *ast.StarExpr:
		g.renderPointerReset(buf, target, underlying.X)
		return
	case *ast.Ident:
		if literal, ok := zeroLiteral(underlying.Name); ok {
			fmt.Fprintf(buf, "%s = %s\n", target, literal)
			return
		}
	}

	g.renderResetterOrZero(buf, target, ident)
}

func (g *codeGenerator) renderPointerIdentReset(buf *bytes.Buffer, target string, ident *ast.Ident) {
	if literal, ok := zeroLiteral(ident.Name); ok {
		fmt.Fprintf(buf, "*%s = %s\n", target, literal)
		return
	}
	if g.hasResetMethod(ident.Name) {
		fmt.Fprintf(buf, "%s.Reset()\n", selectorTarget(target))
		return
	}

	switch underlying := g.knownTypes.underlying(ident).(type) {
	case *ast.ArrayType:
		if underlying.Len == nil {
			fmt.Fprintf(buf, "*%s = (*%s)[:0]\n", target, target)
			return
		}
	case *ast.MapType:
		fmt.Fprintf(buf, "clear(*%s)\n", target)
		return
	case *ast.StarExpr:
		g.renderPointerReset(buf, "*"+target, underlying.X)
		return
	case *ast.Ident:
		if literal, ok := zeroLiteral(underlying.Name); ok {
			fmt.Fprintf(buf, "*%s = %s\n", target, literal)
			return
		}
	}

	g.renderResetterOrPointerZero(buf, target, ident)
}

func (g *codeGenerator) renderResetterOrZero(buf *bytes.Buffer, target string, fieldType ast.Expr) {
	fmt.Fprintf(buf, "if resetter, ok := any(&%s).(interface{ Reset() }); ok {\n", target)
	fmt.Fprintf(buf, "resetter.Reset()\n} else {\n")
	g.renderZeroAssignment(buf, target, fieldType)
	fmt.Fprintf(buf, "}\n")
}

func (g *codeGenerator) renderResetterOrPointerZero(buf *bytes.Buffer, target string, elem ast.Expr) {
	fmt.Fprintf(buf, "if resetter, ok := any(%s).(interface{ Reset() }); ok {\n", target)
	fmt.Fprintf(buf, "resetter.Reset()\n} else {\n")
	g.renderPointerZeroAssignment(buf, target, elem)
	fmt.Fprintf(buf, "}\n")
}

func (g *codeGenerator) renderZeroAssignment(buf *bytes.Buffer, target string, fieldType ast.Expr) {
	fmt.Fprintf(buf, "{\nvar zero %s\n%s = zero\n}\n", exprString(fieldType), target)
}

func (g *codeGenerator) renderPointerZeroAssignment(buf *bytes.Buffer, target string, elem ast.Expr) {
	fmt.Fprintf(buf, "{\nvar zero %s\n*%s = zero\n}\n", exprString(elem), target)
}

func (g *codeGenerator) hasResetMethod(typeName string) bool {
	_, ok := g.resetMethods[typeName]
	return ok
}

func selectorTarget(target string) string {
	if strings.HasPrefix(target, "*") {
		return "(" + target + ")"
	}

	return target
}

func exprString(expr ast.Expr) string {
	var buf bytes.Buffer
	_ = printer.Fprint(&buf, token.NewFileSet(), expr)

	return buf.String()
}

func zeroLiteral(typeName string) (string, bool) {
	switch typeName {
	case "bool":
		return "false", true
	case "string":
		return `""`, true
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
		"byte", "rune",
		"float32", "float64",
		"complex64", "complex128":
		return "0", true
	}

	return "", false
}
