name: go vet test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  statictest:
    runs-on: ubuntu-latest
    container: golang:1.25
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download statictest binary
        run: |
          mkdir -p $GITHUB_WORKSPACE/.tools
          AUTOTESTS_DIR=$(go mod download -json github.com/Yandex-Practicum/go-autotests@v0.13.4 | awk -F'"' '/"Dir":/ {print $4}')
          echo "AUTOTESTS_DIR=$AUTOTESTS_DIR" >> $GITHUB_ENV

      - name: Setup autotest binary
        run: |
          cd "$AUTOTESTS_DIR/cmd/statictest"
          go build -o $GITHUB_WORKSPACE/.tools/statictest
          chmod -R +x $GITHUB_WORKSPACE/.tools/statictest
          mv $GITHUB_WORKSPACE/.tools/statictest /usr/local/bin/statictest

      - name: Run statictest
        run: |
          go vet -vettool=$(which statictest) ./...
